name: TSLplugins
version: '1.0'
main: org.tsl.tSLplugins.TSLplugins
api-version: '1.21'
authors: [ Zvbj ]
description: TSL Server Plugin
folia-supported: true
softdepend: [ PlaceholderAPI ]

commands:
  tsl:
    description: TSL Plugin Main Command
    usage: |
      /tsl advcount refresh <player|all>
      /tsl aliasreload
      /tsl maintenance
      /tsl scale <value|reset>
      /tsl hat
      /tsl ping [player|all [page]]
      /tsl toss [toggle|velocity [value]]
      /tsl ride [toggle]
      /tsl fixghost [radius]
      /tsl list
      /tsl near [range]
      /tsl phantom on
      /tsl phantom off
      /tsl phantom status
      /tsl spec start [delay]
      /tsl spec stop
      /tsl spec add <player>
      /tsl spec remove <player>
      /tsl spec list
      /tsl patrol
      /tsl reload

permissions:
  tsl.visitor.admin:
    description: Visitor mode admin permission
    default: op
  tsl.alias.reload:
    description: Reload command alias config permission
    default: op
  tsl.maintenance.toggle:
    description: Toggle maintenance mode permission
    default: op
  tsl.maintenance.bypass:
    description: Bypass maintenance mode permission
    default: op
  tsl.scale.use:
    description: Use scale command permission
    default: true
  tsl.scale.bypass:
    description: Bypass scale range limit permission
    default: op
  tsl.hat.use:
    description: Use hat command permission
    default: true
  tsl.ping.use:
    description: Use ping command permission
    default: true
  tsl.ping.all:
    description: View all players ping permission
    default: op
  tsl.toss.use:
    description: Use toss entity feature permission
    default: true
  tsl.toss.velocity:
    description: Set toss velocity permission
    default: true
  tsl.toss.velocity.bypass:
    description: Bypass toss velocity limit permission
    default: op
  tsl.toss.bypass:
    description: Bypass entity blacklist permission
    default: op
  tsl.ride.use:
    description: Use ride entity feature permission
    default: true
  tsl.ride.bypass:
    description: Bypass ride blacklist permission
    default: op
  tsl.speed.walk:
    description: Set walk speed permission
    default: op
  tsl.speed.fly:
    description: Set fly speed permission
    default: op
  tsl.fixghost.use:
    description: Use ghost block fix feature permission
    default: true
  tsl.list:
    description: View online player list permission
    default: true
  tsl.near.use:
    description: Use near player query permission
    default: true
  tsl.near.bypass:
    description: Bypass near range limit permission
    default: op
  tsl.phantom.toggle:
    description: Toggle phantom harassment permission
    default: true
  tsl.spec.use:
    description: Use spectator mode permission
    default: op
  tsl.patrol.use:
    description: Use patrol feature permission
    default: op
  tsl.reload:
    description: Reload all plugin config permission
    default: op
  tsl.attribute.add:
    description: Add timed attribute effect permission
    default: op
  tsl.attribute.set:
    description: Set attribute base value permission
    default: op
  tsl.attribute.remove:
    description: Remove attribute effect permission
    default: op
  tsl.attribute.list:
    description: List attribute effects permission
    default: op
  tsl.attribute.clear:
    description: Clear all attribute effects permission
    default: op
  tsl.neko.set:
    description: Set player as neko permission
    default: op
  tsl.neko.reset:
    description: Reset player neko status permission
    default: op
  tsl.neko.list:
    description: List all neko players permission
    default: op
  tsl.mcedia.use:
    description: Use mcedia GUI permission
    default: op
  tsl.mcedia.create:
    description: Create mcedia player permission
    default: op
  tsl.mcedia.delete:
    description: Delete mcedia player permission
    default: op
  tsl.mcedia.list:
    description: List mcedia players permission
    default: op
  tsl.mcedia.set:
    description: Set mcedia video permission
    default: op
  tsl.mcedia.scan:
    description: Scan mcedia players permission
    default: op
  tsl.mcedia.teleport:
    description: Teleport to mcedia player permission
    default: op
  tsl.ss.give:
    description: Give super snowball item permission
    default: op
  tsl.ss.use:
    description: Use super snowball permission
    default: true
  tsl.redfreeze.use:
    description: Use redstone freeze command permission
    default: op
