name: TSLplugins
version: '1.0'
main: org.tsl.tSLplugins.TSLplugins
api-version: '1.21'
authors: [ Zvbj ]
description: TSL服务器的插件喵
folia-supported: true
softdepend: [ PlaceholderAPI ]

commands:
  tsl:
    description: TSL 插件主命令
    usage: |
      /tsl advcount refresh <player|all>
      /tsl aliasreload
      /tsl maintenance
      /tsl scale <数值|reset>
      /tsl hat
      /tsl ping [玩家名|all [页码]]
      /tsl toss [toggle|velocity [数值]]
      /tsl reload

permissions:
  tsl.visitor:
    description: 访客权限，拥有此权限的玩家不会被怪物攻击并发光
    default: false
  tsl.alias.reload:
    description: 重载命令别名配置的权限
    default: op
  tsl.maintenance.toggle:
    description: 切换维护模式的权限
    default: op
  tsl.maintenance.bypass:
    description: 绕过维护模式，允许在维护时进入服务器
    default: op
  tsl.scale.use:
    description: 使用体型调整命令的基础权限
    default: true
  tsl.scale.bypass:
    description: 绕过体型范围限制，可以设置任意体型值
    default: op
  tsl.hat.use:
    description: 使用 Hat 命令的权限
    default: true
  tsl.ping.use:
    description: 使用 Ping 命令查询延迟的权限
    default: true
  tsl.ping.all:
    description: 查看全服玩家延迟排行的权限
    default: op
  tsl.toss.use:
    description: 使用举起生物功能的权限
    default: true
  tsl.toss.velocity:
    description: 设置投掷速度的权限
    default: true
  tsl.toss.velocity.bypass:
    description: 绕过投掷速度范围限制的权限
    default: op
  tsl.toss.bypass:
    description: 绕过实体黑名单限制的权限
    default: op
  tsl.reload:
    description: 重载所有插件配置的权限
    default: op

